STAGES = (
    "resolve_source",
    "collect_metadata",
    "acquire_transcript",
    "normalize_transcript",
    "group_transcript",
    "build_timeline",
    "run_analysis",
    "extract_frames",
    "visual_analysis",
    "highlight_snapshot",
    "comments_fetch",
    "comments_analysis",
    "export_knowledge_package",
)
