import { DEFAULT_BRIDGE_BASE, createClip, createIntake, readTranscript, resolveSource, validateBridgeBase, validatePageUrl } from "./bridge_client.js";

const state = { bridgeBase: DEFAULT_BRIDGE_BASE, pageUrl: "", transcript: null, groups: [], selections: new Map(), requestIds: new Map(), readingMode: false, loadedRecordKey: "", loadSequence: 0, reloadTimer: 0 };
const $ = (selector) => document.querySelector(selector);
const message = { loading: "Loading the current page\u2026", noMatch: "No knowledge record matches the current page.", loaded: "Loaded", copied: "Copied text.", saved: "Clip saved.", highlighted: "Highlight saved.", inbox: "Added to the knowledge inbox; start processing there when ready.", clipFailed: "Clip failed.", inboxFailed: "Could not add to inbox.", readFailed: "Could not read the current record.", bridgeInvalid: "The local Bridge address is invalid.", pageUnsupported: "The current page is not a readable HTTP(S) page." };
function setStatus(value, error = false) { const element = $("#status"); element.textContent = String(value || ""); element.classList.toggle("error", error); $("#retry")?.classList.toggle("hidden", !error); $("#refresh")?.toggleAttribute("disabled", value === message.loading); }
function publicError(error, fallback = message.readFailed) { const code = String(error?.code || "").toLowerCase(); const raw = String(error?.message || ""); if (code === "knowledge_not_found" || /No knowledge record matches the current page/i.test(raw)) return message.noMatch; if (/not a readable HTTP\(S\) page/i.test(raw)) return message.pageUnsupported; if (code === "bridge_invalid" || /bridge|回环主机|凭据、路径|查询参数/i.test(raw)) return message.bridgeInvalid; return fallback; }
function safePageUrl(value) { try { return validatePageUrl(value); } catch { return ""; } }
function pageIdentityUrl(value) { const normalized = safePageUrl(value); if (!normalized) return ""; const url = new URL(normalized); url.searchParams.delete("t"); url.searchParams.delete("start"); return url.toString(); }
async function activePageUrl() { const tabs = await chrome.tabs.query({ active: true, currentWindow: true }); const url = safePageUrl(tabs?.[0]?.url || ""); if (!url) throw new Error("Current page is not a readable HTTP(S) page."); return url; }
function selectionForArticle(article) { const selection = window.getSelection?.(); if (!selection || selection.isCollapsed || !selection.toString().trim()) return ""; if (!article.contains(selection.anchorNode) || !article.contains(selection.focusNode)) return ""; return selection.toString().trim(); }
function rememberSelection(article, group) { const text = selectionForArticle(article); if (text) state.selections.set(Number(group.index), text); return text; }
function selectedText(article, group) { return selectionForArticle(article) || state.selections.get(Number(group.index)) || String(group.text || "").trim(); }
async function seekGroup(group) { const source = state.transcript?.source || {}; if (source.kind !== "video") return; const tabs = await chrome.tabs.query({ active: true, currentWindow: true }); const activeUrl = safePageUrl(tabs?.[0]?.url || ""); if (!activeUrl || pageIdentityUrl(activeUrl) !== pageIdentityUrl(state.pageUrl)) { setStatus("The active page changed. Refresh subtitles before seeking.", true); return; } const url = new URL(activeUrl); const seconds = Math.max(0, Math.floor(Number(group.start) || 0)); url.searchParams.set("t", String(seconds)); await chrome.tabs.update({ url: url.toString() }); setStatus(`Opened video at ${formatTime(seconds)}.`); }
function requestIdFor(group, kind, fingerprint = "") { const knowledgeId = String(state.transcript?.knowledge_id || "unknown"); const key = `${knowledgeId}:${Number(group.index)}:${kind}`; const existing = state.requestIds.get(key); if (!existing || existing.fingerprint !== fingerprint) state.requestIds.set(key, { fingerprint, id: globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}` }); return state.requestIds.get(key).id; }
async function copyText(text) { await navigator.clipboard.writeText(String(text || "")); setStatus(message.copied); }
async function clipGroup(group, article, kind = "clip") { const text = selectedText(article, group); if (!text) throw new Error("This group has no text to clip."); const source = state.transcript?.source || {}; const video = source.kind === "video"; const note = String($("#note")?.value || "").trim().slice(0, 500); const fingerprint = JSON.stringify({ text, note, start: video ? Number(group.start || 0) : null, end: video ? Number(group.end || group.start || 0) : null }); await createClip(state.bridgeBase, { kind, target: { knowledge_id: state.transcript.knowledge_id }, source: { url: source.url || state.pageUrl, title: state.transcript.title || "" }, selection: { text, prefix: "", suffix: "", media_start_seconds: video ? Number(group.start || 0) : null, media_end_seconds: video ? Number(group.end || group.start || 0) : null }, note }, requestIdFor(group, kind, fingerprint)); setStatus(kind === "highlight" ? message.highlighted : message.saved); }
async function intakeGroup(group, article) { const source = state.transcript?.source || {}; if (source.kind !== "web_page") throw new Error("Inbox capture is available only for page text blocks."); const text = selectedText(article, group); if (!text) throw new Error("This group has no text to send."); const requestId = requestIdFor(group, "intake", text); await createIntake(state.bridgeBase, { client_request_id: requestId, source: { kind: "page", url: source.url || state.pageUrl }, capture: { title: state.transcript?.title || "", selected_text: text, visible_text: "" }, preferences: { analysis_profile: "summary", processing_profile: "fast", output_languages: ["source"] }, consent: { user_initiated: true, content_upload_allowed: false } }, requestId); setStatus(message.inbox); }
function formatTime(value) { const total = Math.max(0, Math.floor(Number(value) || 0)); const hours = Math.floor(total / 3600); const minutes = Math.floor((total % 3600) / 60); const seconds = total % 60; return hours ? `${hours}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}` : `${minutes}:${String(seconds).padStart(2, "0")}`; }
function renderGroups() { const container = $("#groups"); const query = $("#search").value.trim().toLowerCase(); const video = state.transcript?.source?.kind === "video"; container.replaceChildren(); const visible = state.groups.filter((group) => `${group.title || ""} ${group.text || ""}`.toLowerCase().includes(query)); if (!visible.length) { const empty = document.createElement("p"); empty.className = "empty"; empty.textContent = video ? "No matching subtitle groups." : "No matching page text blocks."; container.append(empty); return; } for (const group of visible) { const article = $("#group-template").content.firstElementChild.cloneNode(true); const position = article.querySelector(".group-position"); const start = Number(group.start || 0); const end = Number(group.end || start); position.textContent = video ? `${formatTime(start)}-${formatTime(end)}${group.title ? ` | ${group.title}` : ""}` : `Block ${Number(group.position || group.index + 1)}${group.title ? ` | ${group.title}` : ""}`; const seek = article.querySelector(".seek"); seek.classList.toggle("hidden", !video); seek.addEventListener("click", async () => { try { await seekGroup(group); } catch (error) { setStatus(publicError(error, "Could not open the video at this time."), true); } }); const textNode = article.querySelector(".group-text"); textNode.textContent = String(group.text || ""); textNode.addEventListener("mouseup", () => rememberSelection(article, group)); article.querySelector(".copy").addEventListener("click", async () => { try { await copyText(group.text); } catch (error) { setStatus(publicError(error, "Could not copy text."), true); } }); article.querySelector(".clip").addEventListener("click", async () => { try { await clipGroup(group, article); } catch (error) { setStatus(publicError(error, message.clipFailed), true); } }); article.querySelector(".highlight").addEventListener("click", async () => { try { await clipGroup(group, article, "highlight"); } catch (error) { setStatus(publicError(error, message.clipFailed), true); } }); const intake = article.querySelector(".intake"); intake.classList.toggle("hidden", video); intake.addEventListener("click", async () => { try { await intakeGroup(group, article); } catch (error) { setStatus(publicError(error, message.inboxFailed), true); } }); container.append(article); } }
function setReadingMode(enabled) { state.readingMode = Boolean(enabled); document.body.classList.toggle("focus-reading", state.readingMode); const button = $("#readingMode"); if (button) { button.setAttribute("aria-pressed", String(state.readingMode)); button.textContent = state.readingMode ? "Exit focus reading" : "专注阅读"; } chrome.storage.local.set({ readingMode: state.readingMode }).catch(() => {}); }
async function load() { const sequence = ++state.loadSequence; setStatus(message.loading); $("#source").classList.add("hidden"); $("#groups").replaceChildren(); state.selections.clear(); state.requestIds.clear(); try { state.bridgeBase = validateBridgeBase(state.bridgeBase); const pageUrl = await activePageUrl(); const resolved = await resolveSource(state.bridgeBase, pageIdentityUrl(pageUrl)); const match = resolved.matches?.[0]; if (!match) throw new Error(message.noMatch); const transcript = await readTranscript(state.bridgeBase, match.knowledge_id); if (sequence !== state.loadSequence) return; const recordKey = String(transcript.knowledge_id || match.knowledge_id || ""); if (state.loadedRecordKey && state.loadedRecordKey !== recordKey) { $("#search").value = ""; $("#note").value = ""; } state.loadedRecordKey = recordKey; state.pageUrl = pageUrl; state.transcript = transcript; state.groups = Array.isArray(transcript.groups) ? transcript.groups : []; const video = transcript.source?.kind === "video"; $("#source-title").textContent = transcript.title || match.title || "Current knowledge record"; $("#source-url").textContent = pageUrl; $("#search-label").textContent = video ? "Search subtitles" : "Search page text"; $("#search").placeholder = video ? "Search current subtitles" : "Search current page text"; $("#note-label").textContent = video ? "Note for clip/highlight" : "Note for page clip/highlight"; $("#source").classList.remove("hidden"); renderGroups(); setStatus(`${message.loaded} ${state.groups.length} ${video ? "subtitle groups" : "page text blocks"}.`); } catch (error) { if (sequence !== state.loadSequence) return; state.transcript = null; state.groups = []; setStatus(publicError(error), true); } }
function scheduleLoad() { clearTimeout(state.reloadTimer); state.reloadTimer = setTimeout(() => { state.reloadTimer = 0; load(); }, 120); }
window.addEventListener("pagehide", () => { clearTimeout(state.reloadTimer); state.reloadTimer = 0; state.loadSequence += 1; });
async function restoreBridgeBase() { const stored = await chrome.storage.local.get({ bridgeBase: DEFAULT_BRIDGE_BASE }); try { state.bridgeBase = validateBridgeBase(stored.bridgeBase || DEFAULT_BRIDGE_BASE); } catch { state.bridgeBase = DEFAULT_BRIDGE_BASE; } $("#bridgeBase").value = state.bridgeBase; }
async function restoreReadingMode() { const stored = await chrome.storage.local.get({ readingMode: false }); setReadingMode(Boolean(stored.readingMode)); }
$("#refresh").addEventListener("click", load); $("#retry").addEventListener("click", load); $("#search").addEventListener("input", renderGroups); $("#readingMode").addEventListener("click", () => setReadingMode(!state.readingMode)); $("#saveBridge").addEventListener("click", async () => { try { const value = validateBridgeBase($("#bridgeBase").value); state.bridgeBase = value; await chrome.storage.local.set({ bridgeBase: value }); await load(); } catch (error) { setStatus(publicError(error), true); } }); chrome.tabs.onActivated?.addListener(scheduleLoad); chrome.tabs.onUpdated?.addListener(async (tabId, changeInfo) => { if (!changeInfo.url) return; const tabs = await chrome.tabs.query({ active: true, currentWindow: true }); if (tabs?.[0]?.id === tabId) scheduleLoad(); }); await restoreBridgeBase(); await restoreReadingMode(); await load();
